### ISSUE TITLE
Readme.md confuso

### ISSUE THREAD

**Issue by rafaelfaustini** [Kanthus123/Python#1]
O readme ficou um pouco confuso, não entendi se você fez os exercícios do uri judge junto com o curso de udemy, ou se o curso da udemy foi a base em python para fazer os exercícios do Uri Judge

**Comment by Kanthus123** [comment]
Ao meu ver não parece confuso haha, mas eu dei uma alterada para deixar em forma de lista.

Me diz se ficou melhor para o seu entendimento

**Comment by Kanthus123** [comment]
Ahhh, olhando novamente eu entendi o porque da confusão! Espaços em branco não estava dando pulo de linha, adicionei alguns break lines

**Comment by rafaelfaustini** [comment]
Ficou bom, também pode usar o markdown para fazer esses tipos de lista
![image](https://user-images.githubusercontent.com/26970976/56252733-9e10c600-608f-11e9-9050-2679e000be4a.png)

**Comment by rafaelfaustini** [comment]
Como já não existe propósito nesse issue, vou fecha-lo
