### ISSUE TITLE
Sugestão quanto ao Uri Judge

### ISSUE THREAD

**Issue by rafaelfaustini** [Kanthus123/Python#2]
Estive dando uma olhada nos códigos do Uri Judge, seria interessante comentar no código o número da questão no Uri.

**Comment by Kanthus123** [comment]
Verdade, mas nem todas foram feitas na minha conta na época, então eu vou alterar as que eu tiver como achar o código no Uri

**Comment by Kanthus123** [comment]
Quase todas agora tem sua origem, menos a torre de Hanoi.
